const express = require('express')
var userRouter = express.Router()
const controller = require("../controllers/user.controller")
const auth = require ("../middleware/jwtuser")
const trycatchmiddleware = require("../middleware/trycatchmidlware")
userRouter.post('/users/register', trycatchmiddleware(controller.register))
userRouter.post('/users/login' , trycatchmiddleware(controller.login))  
userRouter.get('/users/products',auth,trycatchmiddleware(controller.products))
userRouter.get('/users/products/:id',auth,trycatchmiddleware(controller.productbyid))
userRouter.get('/users/products/category/:categoryname',auth,trycatchmiddleware(controller.productbycategory))
userRouter.post('/users/cart/:id', auth,trycatchmiddleware(controller.cartid))  
userRouter.get('/users/cart/:id',auth,trycatchmiddleware(controller.productincart))
userRouter.post('/users/wishlist/:id',auth,trycatchmiddleware(controller.wishlist))
userRouter.get('/users/wishlist/:id',auth,trycatchmiddleware(controller.wishlistbyget))
userRouter.delete('/users/wishlist/:id',auth,trycatchmiddleware(controller.wishlistdelete))
userRouter.post('/user/payment/:id',auth,trycatchmiddleware(controller.payment))
userRouter.get('/users/payment/success',trycatchmiddleware(controller.sucess))
userRouter.post('/users/payment/cancel',trycatchmiddleware(controller.cancel))
module.exports=userRouter